feat(workflow): set the weight of cpu request of custom containers
caicloud/cyclone pull request #1518
Opened 2020-11-03 03:25 UTC by knight42

**What this PR does / why we need it**:

* Add a field `WorkloadCustomContainerCPUWeight` to `pkg/server/config.CycloneServerConfig`
* `applyResourceRequirements` would adjust the cpu request of the containers according to the above setting

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @zhujian7 

**Release note**:

```release-note
NONE
```

2020-11-03 03:39 UTC, zhujian7 commented on pkg/server/config/config.go
> +	WorkloadCustomContainerCPUWeight int `json:"workload_custom_container_cpu_weight"`
Please add some comments for the field

2020-11-03 04:46 UTC, zhujian7 requested changes

2020-11-03 04:46 UTC, zhujian7 commented on pkg/workflow/workload/pod/builder.go
> +	m.pod.Spec.InitContainers = applyResourceRequirements(m.pod.Spec.InitContainers, requirements, false, config.Config.WorkloadCustomContainerCPUWeight)
Init containers executes one by one, so I think it is not necessary to comply with this rule.

2020-11-03 04:53 UTC, knight42 commented
@zhujian7 PTAL

2020-11-03 06:38 UTC, zhujian7 commented on pkg/server/config/config.go
> +	WorkloadCustomContainerCPUWeight int `json:"workload_custom_container_cpu_weight"`
`CustomContainerCPUWeight` is simpler?

2020-11-03 06:38 UTC, zhujian7 approved these changes

2020-11-03 06:40 UTC, zhujian7 commented
@knight42 please fix the CI.

2020-11-03 08:23 UTC, zhujian7 commented
/cherrypick cps-2.8

2020-11-03 10:16 UTC, knight42 commented
/hold
Leave time for review. @zhujian7 PTAL

2020-11-04 08:28 UTC, knight42 commented
/close

b/c this is not the root cause.

2020-11-04 08:28 UTC, closed without merging